server:
  port: 9001

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: service1
          uri: http://localhost:8011
          predicates:
          - Path=/services/**
        - id: service2
          uri: http://localhost:8012
          predicates:
            - Path=/services/**
        - id: gateway
          uri: http://localhost:9001
          predicates:
            - Path=/gateway/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true # ??? ???? (???) ?? ??
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"